### ISSUE TITLE
Kiste

### ISSUE THREAD

**Issue by rthill** [MrReSc/PhonieboxSetup#1]
Sehr schöne Kiste! Leider ist diese nicht aufgelistet, kannst du mir sagen wo du diese Kiste gekauft hast und welche Modifikationen noch gemacht wurden?

**Comment by MrReSc** [comment]
Hallo, danke für das Kompliment.
Die Kiste ist vom Flohmarkt, darum ist sie nicht aufgeführt.

Für die Löcher in der Kiste habe ich einen Plan in LibreOffice Draw gezeichnet und auf Klebefolie ausgedruckt. So konnte ich die Löcher und die gesprühten Symbole genau machen.
